site_name: JakeSiewJK64
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-274394082'}
  highlightjs: true
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
